Controllers/Backend/ConnectBaseController.php

Please also check https://github.com/shopware/Mosaic/pull/1807
This change is necessary, as the auto-login does not create a proper SBP token. Right now the logout does not work properly, otherwise the users who are coming from Shopware would always get a nasty error message when they try to login, and they have to login manually.

[CON-4170] Don't auto-login the user, it will create problems with SBP

---

Commands/ApiEndpointCommand.php
Tests/Shopware/Connect/Command/ApiEndpointCommandTest.php

The problem was that the `parse_url` did not worked well if the host only contained `sn.connect.local`.

NTR - Fix connect:endpoint:set command

---

Components/ProductToShop.php

Didn't find a way how to simulate described bug, but I made some improvements and probably this problem won't occur in the future.
**First**: when option doesn't exist in merchant shop, PropertyValue doesn't exist as well. So we don't need to call DB in this case. 
**Second**: I've changed ```$valueRepo->findOneBy(['optionId' => $option->getId(), 'value' => $property->value]);``` to ```$valueRepo->findOneBy(['option' => $option, 'value' => $property->value])```, because there isn't setter and getter for optionId. It's just e property mapped to column "optionID". this column is also mapped to property "option" in this class. It has many to one connection. So I prefer to use ```PropertyValue::option``` instead of ```PropertyValue::optionID```.

CON-4591 Improved property creation

---

.sw-zip-blacklist

This adds files which will be ignored by the shopware release process

NTR - Add files to .sw-zip-blacklist

---

Components/ConnectExport.php
Components/Helper.php
Controllers/Backend/ConnectBaseController.php

Don't need to generate stream assignment changes for products which are not exported to Connect system anymore.
Connect will skip them, but don't need to replicate superfluous changes.

CON-4611 Check exported product on removeStreams

---

Components/ProductToShop.php

In some cases we got error: QLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '639-7' for key 'articleID' in
With addCategory method this is not possible, because it will check if category is already added.

CON-4735 Use addCategory instead of setCategories

---

Components/ProductToShop.php
Tests/Integration/Components/ProductToShopTest.php

Always clear entity manager, because $article->getDetails() returns
more than 1 detail, even when all of them were removed except main one.

NTR Fix delete variants

---

Models/Connect/RemoteCategory.php

This is needed because when someone try to update SwagConnect plugin, doctrine proxies contain localCategoryId and localCategory
proeprties. Then plugin update fails, shopwre backend will be reloaded, but got blank screen.

NTR Revert removed properties in RemoteCategory

---

Components/ProductQuery/LocalProductQuery.php
Components/ProductToShop.php
Tests/Integration/Components/ProductQuery/LocalProductQueryTest.php
Tests/Integration/Components/ProductToShopTest.php
Tests/Legacy/Shopware/Connect/Component/ProductQuery/LocalProductQueryTest.php

Collect variant options only where configurator_set_id column in s_articles table is not null

CON-4871 Fill $product->variants when configuratorSet exists

---

Bootstrap/SubscriberRegistration.php
Components/ProductStream/ProductSearch.php
Components/ProductStream/ProductStreamService.php
Subscribers/CronJob.php
Subscribers/ServiceContainer.php
Tests/Integration/Subscribers/ServiceContainerTest.php
Tests/Unit/Subscribers/CronJobTest.php
Tests/Unit/Subscribers/ServiceContainerTest.php

Storefront namespace is designed to be used only in shopware frontend,
but we need to fetch articles/detal by stream id during stream export in backend.
Problem is that ShopContext is using Shop entity and it will break current session in DB.
With this PR Storefront namespace is not used anymore as a dependency.

CON-4922 Refactor storefront usage in stream export

---

Components/ProductToShop.php
Tests/Integration/Components/ProductToShopTest.php

if the supplier has taxes with values the merchant hasn't no tax
was assigned to the Product in ProductToShop.
Now a new Tax with the value of the supplier is created and assigned.

CON-4907: create Tax if it not exists in ToShop

---

Subscribers/Article.php
Tests/Functional/Subscribers/ArticleTest.php
Tests/Functional/Subscribers/_fixtures/articleWithPriceGroup.sql

before the ArticleSubscriber used ->fetchColumn
that returns the result of the first row as string
after that we called export() with that
result
but exports() expects an array as input
with executeQuery()->fetchAll(\PDO::FETCH_COLUMN)
this query will return an array of articleIds

CON-4955: ArticleSubscriber uses right FetchMode

---

Components/CategoryResolver.php
Components/ProductToShop.php
Tests/Integration/Components/ProductToShopTest.php
Tests/Integration/Components/_fixtures/connect_item_with_two_categories.sql

Before local categories with only one article get deleted if these
article receives change, because we remove all assigned connect
categories in the beginning of ProductToShop::insertOrUpdate()
now this is handled properly in CategoryResolver::storeRemoteCategories
Another problem was that we assigned parent categories to all articles
this is right for b4a but could make problems for everybody else
now the parent category gets deleted if we assign a new category
this works also for b4a because they want the posibillity to assign
articles to not leaf categories

CON-4969: fixed category assignment for categories with one article

---

Components/ConnectExport.php

Currently this makes problems in b4a shop with deleting a
category with many childs and many products
after this change articleIds should be fetched "in batches"
per category
this could still make problems because b4a assigns all
products to every parent category
IMHO we can only really test this in production :(

NTR: fixed mark Products in deleted Categories

---

Components/VariantConfigurator.php

this has thrown exceptions on staging
i guess this could also happen if supplier has old plugin version and
merchant newer

NTR: check if configuratorSet is empty

---

Components/CategoryResolver.php
Components/CategoryResolver/AutoCategoryResolver.php
Components/CategoryResolver/DefaultCategoryResolver.php
Tests/Integration/Components/CategoryResolver/DefaultCategoryResolverTest.php
Tests/Integration/Components/ProductToShopTest.php
Tests/Integration/Components/_fixtures/categories.sql
Tests/Integration/Components/_fixtures/one_connect_to_local_category.sql
Tests/Integration/Components/_fixtures/one_item_category_with_wrong_stream.sql
Tests/Unit/Models/RemoteCategoryTest.php

before we don't create new subcategories if the parent connect category
is assigned
now it is checked that all subcategories of each assigned remote
category are there and if not they are created

CON-4973: subcategories in default category resolver are created

---

Components/ConnectExport.php
Tests/Integration/Components/ConnectExportTest.php

before we fired the whole query with 5 joins and get the rowCount
now we use a proper Count-Query
increases loading speed for ExportList from >30s to <300ms for 1M products

CON-4978: fixed count for connect items in export window

---

Subscribers/Checkout.php

Some of the products are missing when there are more then 1 supplier
during checkout. Final all order will contain everything, but in confirm page
remote shipping is displayed only for the last supplier. This problem occurs,
because SDK order contains only products from last supplier when plugin makes
checkProducts call.

CON-5114 Fixed preparation of Connect order during checkout

---

Components/BasketHelper.php

Add local shipping costs price even when basket contains only connect products.
This is needed when at least one supplier has shipping cost type = all or filter.
Then endcustomer has to pay merchant shipping costs and shipping costs provided by
other suppliers remotely.

CON-5110 Add local shipping costs when necessary

---

Subscribers/Connect.php

if an update for connect was available we prompted it to the user
with a link to update the plugin
if the user don't has acess to pluginmanager it crashed
Added an check for the update privilege of the pluginmanager resource
but it looks like the different privileges are ignored for pluginmanager
e.g. i can acess the plugin manager and store if i don't have
read rights and update an plugin if i don't have update rights

CON-5096: added check for pluginmanager privileges

---

Components/ProductStream/ProductStreamService.php

problem was we checked each article if it is in an exported stream
when we create stream its status is 'pending'
pending wasn't in the exported statuses so articles
in this stream where not exported
in the end we set status of stream we created to 'exported'
in the next run the articles would be exported

CON-5155: dynamic stream is exported with first CRON run

---

Components/ProductToShop.php

in some cases product->lastStock is null and it is not used for the
lastStock attribute of the Aticle
now the same logic is used for detail as for article

NTR: fixed 5.4 compatibility

---

Services/MenuService.php

While resetting the exchange settings we reset the menu too by finding the top level menu entry by it's name.
If you're connected to a custom marketplace the label of the menu entry is changed to the marketplace's name and the MenuRepository will return null.

ntr - find menu entry by class not by label

---

Components/ImageImport.php
Tests/Integration/Components/ImageImportTest.php

B4A had performance problems with this one because one product had 750
variants we wanted to import all images from the variants in one cron run
now the limit takes the number of variants as the limit
also the main article images are just imported for the main variant

CON-5301: fixed limits for Image Import over cron
